name: trivia_app
description: This is an introductory workshop to Flutter,
  the open-source mobile application development created by Flutter developers from TagesJump.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  # Lint
  lint: ^1.3.0
  # Http client
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true