name: trivia_app
description: This is an introductory workshop to Flutter,
  the open-source mobile application development created by Flutter developers from TagesJump.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  flutter_bloc: ^6.0.6
  get_it: ^4.0.4
  # Lint
  lint: ^1.3.0
  # Http client
  http: ^0.12.2
  # UI
  swipeable_card: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  injectable: ^1.0.4
  injectable_generator: ^1.0.4
  freezed: ^0.12.1
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0

flutter:
  uses-material-design: true
