name: trivia_app
description: This is an introductory workshop to Flutter,
  the open-source mobile application development created by Flutter developers from TagesJump.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  flutter_bloc: ^6.1.1
  # Lint
  lint: ^1.3.0
  # Http client
  http: ^0.12.2
  # UI
  swipeable_card: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
